### ISSUE TITLE
[Insight] Sensitive data should not be present in non-parameter configuration files - in app/config/security.yml, line 18

### ISSUE THREAD

**Issue by hajri-aymen** [symfonytn/symfonyStandard#6]
**[in app/config/security.yml, line 18](https://github.com/symfonytn/symfonyStandard/blob/11114dfb9080436ff335c6b4c3118a17fd7236ba/app/config/security.yml#L18)**

> A sensitive data has been detected in your configuration file (`password` parameter). You should consider storing it in a single parameter file.

```
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/d35dc9e1-06f0-492e-96b3-1f8f3ecb24a3/analyses/1)_
